---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/MAGIC/web-map-inventory/-/settings/ci_cd

# = Secret variables
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensitive values are represented by "[Sensitive]"
#
# - PyPi (production)
# > PYPI_PASSWORD: "[Sensitive]"
#
# - PyPi (staging)
# > PYPI_TEST_PASSWORD: "[Sensitive]"
#
# - Sentry
# > SENTRY_AUTH_TOKEN: "[Sensetive]"
# > SENTRY_DSN: "[Sensetive]"


# == Global settings ==

stages:
  - test
  - lint
  - build
  - publish
  - deploy

variables:
  APP_NAME: magic-map-layers-airflow
  PYPI_USERNAME: british-antarctic-survey
  PYPI_TEST_USERNAME: british-antarctic-survey
  SENTRY_ORG: antarctica
  SENTRY_PROJECT: web-map-inventory

image:
  name: docker-registry.data.bas.ac.uk/magic/web-map-inventory:latest
  entrypoint: [""]

# == Jobs ==

test-app:
  stage: test
  variables:
    FLASK_ENV: testing
  before_script:
    - "touch .env"
  script:
    - "pytest -o junit_family=xunit2 --junitxml=test-results.xml"
  artifacts:
    reports:
      junit: test-results.xml

pep8-app:
  stage: lint
  script:
    - "flake8 ."

bandit-app:
  stage: lint
  script:
    - "bandit -r ."

build-app:
  stage: build
  script:
    - "python setup.py sdist bdist_wheel"
  artifacts:
    name: "$CI_BUILD_TOKEN-build"
    paths:
      - dist
    expire_in: 1 month

publish-app-stage:
  stage: publish
  script:
    - "python -m twine upload --repository-url https://test.pypi.org/legacy/ --username $PYPI_TEST_USERNAME --password $PYPI_TEST_PASSWORD --disable-progress-bar --verbose dist/*"
  only:
    - master

publish-app-prod:
  stage: publish
  script:
    - "python -m twine upload --username $PYPI_USERNAME --password $PYPI_PASSWORD --disable-progress-bar --verbose dist/*"
  only:
    - tags

sentry-stage:
  stage: deploy
  image:
    name: getsentry/sentry-cli
    entrypoint: [""]
  script:
    - "sentry-cli releases new --finalize $CI_COMMIT_SHA"
    - "sentry-cli releases deploys $CI_COMMIT_SHA new -e staging"
  only:
    - master

sentry-prod:
  stage: deploy
  image:
    name: getsentry/sentry-cli
    entrypoint: [""]
  script:
    - "sentry-cli releases new --finalize $CI_COMMIT_SHA"
    - "sentry-cli releases deploys $CI_COMMIT_SHA new -e production"
  only:
    - tags
